### ISSUE TITLE
Qbittorrent, Error while getting torrent info - Failed to establish a new connection: [Errno 111]

### ISSUE THREAD

**Issue by Namlee123** [anasty17/mirror-leech-telegram-bot#1414]
**Describe the bug**
I sometimes have problems using qbittorrent.
1. Torrent downloads about 50-90%, then an error occurs, the torrent is stuck.
2. Only crashes with some torrents, not all.

**File  Log:**
```
2023-03-22 07:04:53,544 - bot - INFO - https://nyaa.si/download/1651818.torrent
2023-03-22 07:04:56,326 - bot - INFO - QbitDownload started: [Moozzi2] Shokei Shoujo no Virgin Road [ x265-10Bit Ver. ] - TV + SP - Hash: 785ebf72f12251a9ee8e518d9f0e2e0afdf3bba9
2023-03-22 07:05:21,310 - web.wserver - INFO - Verified! Hash: 785ebf72f12251a9ee8e518d9f0e2e0afdf3bba9
2023-03-22 07:13:54,660 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Uploaded To G-Drive: The.Dark.Crystal.1982.PROPER.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT
2023-03-22 07:13:56,388 - bot - INFO - Done Uploading The.Dark.Crystal.1982.PROPER.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT
2023-03-22 07:13:56,653 - bot - INFO - Cleaning Download: /usr/src/app/downloads/63963
2023-03-22 07:14:25,046 - bot - INFO - https://nyaa.si/download/1651820.torrent
2023-03-22 07:14:28,050 - bot - INFO - QbitDownload started: [Moozzi2] Boku no Hero Academia S4 [ x265-10Bit Ver. ] - TV + SP - Hash: 1c597b25b0f0bd1ff617016fd366b667c5b7a3c7
2023-03-22 07:14:51,535 - web.wserver - INFO - Verified! Hash: 1c597b25b0f0bd1ff617016fd366b667c5b7a3c7
2023-03-22 07:26:26,450 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31a53730d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/torrents/info
2023-03-22 07:26:26,479 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-245' coro=<setInterval.__setInterval() done, defined at /usr/src/app/bot/helper/ext_utils/bot_utils.py:50> exception=APIConnectionError('Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host=\'localhost\', port=8090): Max retries exceeded with url: /api/v2/torrents/info (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x7f31a549d810>: Failed to establish a new connection: [Errno 111] Connection refused\'))"))')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f31a549d810>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v2/torrents/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31a549d810>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 466, in _request_manager
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 532, in _request
    response = self._session.request(
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 679, in request
    return super(QbittorrentSession, self).request(method, url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v2/torrents/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31a549d810>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 56, in __setInterval
    await self.action()
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/qbit_downloader.py", line 201, in __qb_listener
    if len(await sync_to_async(client.torrents_info)) == 0:
  File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 292, in sync_to_async
    return await future if wait else future
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/decorators.py", line 119, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/decorators.py", line 92, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/torrents.py", line 1810, in torrents_info
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 390, in _post
    return self._request_manager(
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 490, in _request_manager
    raise APIConnectionError(error_message, response=response)
qbittorrentapi.exceptions.APIConnectionError: Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v2/torrents/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31a549d810>: Failed to establish a new connection: [Errno 111] Connection refused'))"))
2023-03-22 07:26:31,426 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31a552a620>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/torrents/info
2023-03-22 07:26:31,431 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31dd59e500>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/torrents/info
2023-03-22 07:26:31,432 - bot - ERROR - Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v2/torrents/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31a54cc0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))")): Qbittorrent, Error while getting torrent info
2023-03-22 07:26:31,437 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31a54d6cb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/torrents/info
2023-03-22 07:26:31,441 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31a549cac0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/torrents/info
2023-03-22 07:26:31,442 - bot - ERROR - Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v2/torrents/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31a54cfc70>: Failed to establish a new connection: [Errno 111] Connection refused'))")): Qbittorrent, Error while getting torrent info
2023-03-22 07:26:31,445 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31a54c53f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/torrents/info
2023-03-22 07:26:31,449 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31a5371f30>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/torrents/info
2023-03-22 07:26:31,450 - bot - ERROR - Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /api/v2/torrents/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31a53d2c80>: Failed to establish a new connection: [Errno 111] Connection refused'))")): Qbittorrent, Error while getting torrent info
```

**Comment by anasty17** [comment]
Send log file

**Comment by anasty17** [comment]
do u know what i do with who report from modified repo?

**Comment by Namlee123** [comment]
I deployed your repo yesterday, I still get this error with a few torrents but I didn't save its recent logs.
The error I'm getting is still the same as the 3/22 log.
[loga.1.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11094244/loga.1.txt)

**Comment by anasty17** [comment]
> I deployed your repo yesterday, I still get this error with a few torrents but I didn't save its recent logs. The error I'm getting is still the same as the 3/22 log. [loga.1.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11094244/loga.1.txt)

i didn't check ur log file yet. but ur code is not up tot date!

**Comment by Namlee123** [comment]
> 

"but ur code is not up to date!"
I don't understand the meaning of this sentence. Could you please elaborate a little more?

**Comment by Namlee123** [comment]
@anasty17 , Can you please tell me the versions you use in the repo:
qbittorrent-nox
qbittorrent-api

**Comment by Namlee123** [comment]
> update ur code! ur code is not up to date. u know how forks on github works ? u know how to update ur code ? u know how to pull new commits ? if u don't then learn them then come and open issue

@anasty17 
Those are the basics that I knew from day one using github.
Maybe due to language gap, I misunderstood what you mean (Updated code from another source).
I assure you, I use your repo with the latest commit.

But some torrents (V1) still fail to connect to receive information.
I want to ask did you use the latest qbittorrent-api version or an older version in docker?
I don't know if the error is from your repo or with the qb-api command, but I'm looking to downgrade.
Currently I use qbittorrent-api latest version from rmartin16 (2023.3.44) but still error.

Logfile: 2023-03-29:
[logb.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11102008/logb.txt)

**Comment by anasty17** [comment]
Qbittorrent-api in requirements and always latest. In docker Qbittorrent-nox latest version which is 4.5.2. 
I will try links from log. I hope i can produce this issue. But seems from previous log there was old log! Old log mean ur code is not on latest commit

**Comment by anasty17** [comment]
Send the torrent file to tg group

**Comment by Namlee123** [comment]
Hi, @anasty17 

1. I tried to modify the bot._int_.py file to show DEBUG logs:
qbClient(host='http://localhost:8090', FORCE_SCHEME_FROM_HOST=True) to force use http scheme.

2. I noticed "XXX" is repeated periodically from the start of the torrent task, but the Bot is still working properly.
After a period of time, "XXX" is no longer cyclic. Now the bot is crashing when connecting to the web-UI

3. This is my guess, the problem might be in urllib3, as I noticed something unusual from "POST" requests. Maybe: The server received two POST requests but something interfered with the response of the first response.

4. I will send you 2 log_DEBUG files,
Start torrenting until it's done:  [No_Er.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11112319/No_Er.txt)
Start torrenting until error: [Er.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11112330/Er.txt)
So you can assess the issue and see the POSTs in action.

**Comment by Namlee123** [comment]
> Send the torrent file to tg group
Most of this torrent-v1 belongs to Tracker with private, non-public. and it has a pretty big capacity of 100Gb-1Tb. but the amount of seeds delivery is extremely high 50-100MB.
Unfortunately, I can't share it publicly, I must always plant the seeds until the ratio is reached. that's their rule. Please forgive me for this.

**Comment by anasty17** [comment]
U can send it in pm. If I can't produce the error then i can't fix it.

**Comment by anasty17** [comment]
Fixed i will push tomorrow. U can edit connection_speed to 30 instead of -1. That's it

**Comment by Namlee123** [comment]
I don't know if your error is the same as mine. It's like a game of chance.
I got this error with torrents: about 300GB large, about 150 subfiles (about 2GB each). High download speed.
I tried downloading three times again - one 200GB torrent - 100MB/s VPS - 1 task/bot.
Results 2 times failed, 1 time successful.

I will send you 2 torrent (1.5TB) files you can download by splitting the size to fit VPS hosting conditions.
You can stop the torrent when it goes to UPLoad mode, because I see this error only during download.

I have attached a few links that I found, possibly related to this issue, for your reference:
https://github.com/python/cpython/issues/85517

ConnectionSpeed: I have set it to 10 from the start of the installation, the value 30 is the default, the old version is 20.
Qb.config
```
[Application]
MemoryWorkingSetLimit=512

[BitTorrent]
Session\AddExtensionToIncompleteFiles=true
Session\AddTrackersEnabled=false
Session\AnnounceToAllTrackers=true
Session\AnonymousModeEnabled=false
Session\AsyncIOThreadsCount=8
Session\ConnectionSpeed=10
Session\DHTEnabled=true
Session\DiskCacheSize=-1
Session\GlobalDLSpeedLimit=0
Session\GlobalMaxRatio=-1
Session\GlobalMaxSeedingMinutes=-1
Session\GlobalUPSpeedLimit=0
Session\HashingThreadsCount=1
Session\IgnoreSlowTorrentsForQueueing=false
Session\IncludeOverheadInLimits=false
Session\LSDEnabled=true
Session\MaxActiveCheckingTorrents=3
Session\MaxActiveDownloads=6
Session\MaxActiveTorrents=8
Session\MaxActiveUploads=2
Session\MaxConnections=500
Session\MaxConnectionsPerTorrent=100
Session\MaxConcurrentHTTPAnnounces=50
Session\MaxRatioAction=0
Session\MaxUploads=6
Session\MaxUploadsPerTorrent=2
Session\MultiConnectionsPerIp=true
Session\PexEnabled=true
Session\PerformanceWarning=true
Session\Preallocation=false
Session\QueueingSystemEnabled=false
Session\SlowTorrentsDownloadRate=2
Session\SlowTorrentsInactivityTimer=600
Session\SlowTorrentsUploadRate=2
Session\StopTrackerTimeout=5
TrackerEnabled=true

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=4

[Preferences]
Advanced\DisableRecursiveDownload=false
Advanced\RecheckOnCompletion=false
Advanced\trackerPortForwarding=true
General\PreventFromSuspendWhenDownloading=true
General\PreventFromSuspendWhenSeeding=true
Search\SearchEnabled=true
WebUI\BanDuration=3600
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=false
WebUI\Enabled=true
WebUI\HTTPS\Enabled=false
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=false
WebUI\MaxAuthenticationFailCount=10
WebUI\Port=8090
WebUI\SecureCookie=false
WebUI\SessionTimeout=3600
WebUI\UseUPnP=true
```

**Comment by anasty17** [comment]
Yes please send the files

**Comment by anasty17** [comment]
u have tried increase MemoryWorking limit ?

**Comment by Namlee123** [comment]
> u have tried increase MemoryWorking limit ?

Hi, Anas.
Yes, I have upgraded to 2048, but the problem is still the same.
Same torrent file, times when downloading fails, sometimes working properly. Like a game of chance.

I'm not sure, because I'm not an expert in programming network protocols, but I'm thinking about the problem:
1. request too often. A delay is required for requests. sleep(1).
2. the server detect the request client is python, so reject. add User-Agent in header to handle this.
These are my personal opinions.

**Comment by anasty17** [comment]
I don't think thise are the cause but i will try. This from qbitorrent latest it's not stable yet. But i will do my best to handle it. U can add the download and delete the status message requests will be less

**Comment by LuisAlfonsoB** [comment]
I had similar error in logs and I fixed it by simply setting maxconnections to 10 in qbit config.. no more errors but probably you could get away with higher number..I don't know. I hope this helps.
![image](https://user-images.githubusercontent.com/119376216/230522081-c620916c-0221-4a33-9caf-4bd0ad90c00f.png)

**Comment by anasty17** [comment]
@Namlee123 update to latest and test

**Comment by Namlee123** [comment]
> @Namlee123 update to latest and test

Hi @anasty17 
I updated the repo yesterday,
I tried running on pc (Ram 10-20%) but after about 12h running (12 task-qbit, 8 task-aria2).
Qbit still gives error.
I did not test Rclone, but the rest of the functions work very well.
![Capture](https://user-images.githubusercontent.com/92989894/230723406-5a96f9dd-4eca-4701-8b48-2e3fc75204db.PNG)

**Comment by anasty17** [comment]
> > @Namlee123 update to latest and test
> 
> Hi @anasty17 I updated the repo yesterday, I tried running on pc (Ram 10-20%) but after about 12h running (12 task-qbit, 8 task-aria2). Qbit still gives error. I did not test Rclone, but the rest of the functions work very well. ![Capture](https://user-images.githubusercontent.com/92989894/230723406-5a96f9dd-4eca-4701-8b48-2e3fc75204db.PNG)

User another port. Or try on vps

**Comment by Namlee123** [comment]
Hi @anasty17 
I use amazon vps but sometimes it still has the same error as above.
Currently, I open the PORT by default of the repo.
Qbit: 8090
Base_URL_Port: 80
Can you give me a little hint? should i change the port on both, or a specific one?

**Comment by anasty17** [comment]
No don't open 8090 port
